apiVersion: v1
kind: Pod
metadata:
  name: my-node
spec:
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: my-container
    image: nginx
  spec:
  nodeSelector:
